# This is the configuration used to check the rubocop source code.
require: rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'config/environments/*'
    - 'config/spring.rb'
    - 'db/**/*'
    - 'lib/tasks/annotate_models.rake'
    - 'log/**/*'
    - 'shell/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/support/database_cleaner.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6

Bundler/OrderedGems:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments