# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

AllCops:

  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'shell/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/puma.rb'
    - 'db/**/*'

Documentation:
  Enabled: false

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false
