default:
  menubar: false
  toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image table'
  plugins:
    - image
    - link
    - lists
    - table
    - contextmenu