name: Workflow for changes in the main branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Prepare database
      env:
        RAILS_ENV: "test"
        DATABASE_URL: "postgres://postgres@localhost:5432/myinterviews_test"
        RUBYOPT: "-W:no-deprecated -W:no-experimental" # Suppress Rails 6 deprecation warnings for ruby 2.7
      run: |
        bundle exec rails db:schema:load --trace
        bundle exec rails db:migrate

    - name: Check test factories
      run: bundle exec rake factory_bot:lint

    - name: Run tests
      env:
        RAILS_ENV: "test"
        DATABASE_URL: "postgres://postgres@localhost:5432/myinterviews_test"
        RUBYOPT: "-W:no-deprecated -W:no-experimental" # Suppress Rails 6 deprecation warnings for ruby 2.7
      run: bundle exec rspec